/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DisplayGPS.java
 *
 * Created on Jul 17, 2010, 11:16:24 AM
 */
package org.kwansystems.rocketometer;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author chrisj
 */
public class DisplayGPS extends javax.swing.JFrame implements GPSListener {
  boolean connected = false;
  ReadGPS R;
  String latestText;
  String nextNMEA;

  /** Creates new form DisplayGPS */
  public DisplayGPS() {
    R = new ReadGPS();
    R.setListener(this);
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    kGPSCanvas1 = new org.kwansystems.rocketometer.KGPSCanvas();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    BtnConnect = new javax.swing.JToggleButton();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    javax.swing.GroupLayout kGPSCanvas1Layout = new javax.swing.GroupLayout(kGPSCanvas1);
    kGPSCanvas1.setLayout(kGPSCanvas1Layout);
    kGPSCanvas1Layout.setHorizontalGroup(
      kGPSCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 284, Short.MAX_VALUE)
    );
    kGPSCanvas1Layout.setVerticalGroup(
      kGPSCanvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 289, Short.MAX_VALUE)
    );

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "PRN", "Az", "El", "Strength"
      }
    ));
    jScrollPane1.setViewportView(jTable1);

    BtnConnect.setText("Connect");
    BtnConnect.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BtnConnectActionPerformed(evt);
      }
    });

    jLabel1.setText("jLabel1");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(kGPSCanvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(BtnConnect)
          .addComponent(jLabel1))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(kGPSCanvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
              .addComponent(jLabel1)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(BtnConnect))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void BtnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConnectActionPerformed
      if (!connected) {
        System.out.println("Trying to connect...");
        try {
          R.connect("COM5", 115200);
          connected=true;
          System.out.println("Connected");
        } catch (Exception ex) {
          System.out.println("Failed to connect: "+ex.toString());
        }
      } else {
        //No disconnect yet
        System.out.println("Disconnecting...");
        R.disconnect();
        System.out.println("Disconnected");
        connected=false;
      }
    }//GEN-LAST:event_BtnConnectActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new DisplayGPS().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton BtnConnect;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private org.kwansystems.rocketometer.KGPSCanvas kGPSCanvas1;
  // End of variables declaration//GEN-END:variables
  public void ParseNMEA(String NMEA) {
    if(NMEA.charAt(0)=='$') {
      String[] pieces=NMEA.split("\\*");
      pieces=pieces[0].split(",");
  //   0 1 2  3  4  5   6 7 4  5   6 7 4  5   6 7 4  5   6 7
//$GPGSV,3,2,12,31,34,051,,13,19,297,,04,05,317,,14,03,104,*7B
      if(pieces[0].equals("$GPGSV")) {
        int nLines=Integer.parseInt(pieces[1]);
        int thisLine=Integer.parseInt(pieces[2])-1;
        int nSats=Integer.parseInt(pieces[3]);
        int[] prn=new int[4];
        int[] az=new int[4];
        int[] el=new int[4];
        int[] strength=new int[4];
        try {
          for(int i=0;i<4;i++) {
            jTable1.setValueAt(pieces[4+4*i], i+4*thisLine, 0);
            jTable1.setValueAt(pieces[5+4*i], i+4*thisLine, 1);
            jTable1.setValueAt(pieces[6+4*i], i+4*thisLine, 2);
            jTable1.setValueAt(pieces[7+4*i], i+4*thisLine, 3);
          }
        } catch (Exception E) {}

      }
    } else {
      jLabel1.setText(NMEA);
    }
  }
  public void listen(String S) {
    latestText+=S;
    int w=latestText.indexOf(0x0A);
    if(w>0) {
      String NMEA=latestText.substring(0, w);
      latestText=latestText.substring(w+1);
      ParseNMEA(NMEA);
      System.out.println(NMEA);
    }
  }
}
